cityofaustin/atd-mobile-signals-work-orders

- .netlify
> Netlify Deploy

- .netlify
- README.md
- package-lock.json
- package.json
- src/App.js
This is the very basic first step to getting Knack working within React.
- We use a library called [react-load-script](https://www.npmjs.com/package/react-load-script) to load the Knack.js third-party [embed code](https://www.knack.com/developer-documentation/#load-external-javascript-files). Once that Knack.js script loads, it looks for the `app_id` config variable from the global window. Knack.js makes a new request with our app specific info and their server returns a `Knack` object with metadata about the Knack app.
- Once we have the `Knack` object, we can use its [helper function](https://www.knack.com/developer-documentation/#retrieving-user-properties-utility), `Knack.getUserToken()` to get the session token for the current user. This allows us to construct our own request to the …
> Connect to Knack API

- src/Home.js
- src/MarkingsDetail.js
> Autoload work order details

- package-lock.json
- package.json
- src/components/App.js
- src/components/NewWorkOrder/formConfig.js
- src/components/NewWorkOrder/index.js
- src/constants/api.js
- src/queries/api.js
- Updating the app ID to reflect the environment rebuild and other fallout...
- Pushing forward with the new work order AJAX autocompletes for asset type options
- Add multiselect UI for work Scheduled Work Type
Closes #47
> Finish New Work Order (step 1)

- src/styles/Login.css.js
> change to layout from grid to flexbox

- package-lock.json
- package.json
- src/components/App.js
Submitting this very small PR to establish theme for the app. So far, I've just pulled the colors from `constants/colors.js` and `styles/Login.css.js` and exposed them to all components via the `ThemeProvider`, which uses the Context API under the hood. 
For reference documentation: https://emotion.sh/docs/theming 
Maybe this will make updating styles easier going forward.
> Application wide themes

- package-lock.json
- package.json
- src/components/WorkOrder/EditNew.js
- src/queries/api.js
Closes #54, specifically https://github.com/cityofaustin/react-knack/issues/54#issuecomment-457296850
> Fix bug on My Work Orders after first logging in

- src/components/App.js
- src/components/WorkOrder/Submit.js
- src/components/WorkOrderDetails.js
- src/queries/api.js
Closes #28 
I noticed that it didn't make sense to see the Edit & Submit buttons after a Work Order has been submitted, so I started a PR for that, #74. Didn't want to get too stuck on it. It's all working but the query errors on a 401 Unauthorized. I need to look into that more.
> Submit work order

- package-lock.json
- package.json
- src/queries/api.js
_Closes #70_ 
Before, the form values being used for technicians was an id to a different their account ID object. The high level account object. The proper form value for a technician is from the "Technician | AMD" table.
Would never have figured this out without Knack support.
> Support Technician Multi select bug fix

- src/components/App.js
- src/components/Shared/dateTimeFieldHelpers.js
- src/components/WorkOrder/DateTimeRangePicker.js
- src/components/WorkOrder/NewTimeLog.js
- src/components/WorkOrder/TimeLog.js
- src/components/WorkOrder/TimeLogDateTimeFields.js
- src/components/WorkOrder/formConfig.js
- src/components/WorkOrderDetails.js
- src/queries/api.js
- src/queries/fields.js
> Time Log Form

- src/components/Form/SubmitButton.js
- src/components/WorkOrder/NewTimeLog.js
- src/components/WorkOrder/TimeLogDateTimeFields.js
> New Time Log Date Validation

- src/components/WorkOrder/formConfig.js
> Reorder assets

- src/components/WorkOrder/AssignTechnicianFields.js
- src/components/WorkOrder/formDataInitialState.js
_Closes #76_
Removes the select option and updates initial form state.
> Default new work orders to be self-assigned

- .prettierrc
- package-lock.json
- src/components/MyWorkOrders.js
> 64 add spinner and empty state

- .prettierrc
- package-lock.json
- src/components/AllWorkOrders.js
- src/components/App.js
- src/components/Home.js
- src/components/MyWorkOrders.js
- src/queries/api.js
- src/queries/fields.js
> 37 All Work Orders

- src/components/MyWorkOrders.js
Closes #109 
I used the same Bootstrap styles used for the buttons in the Work Order Details view in case any other buttons need to be added in the future.
> Add New Work Order button to My Work Orders page

- package-lock.json
- src/styles/App.css
> fixed android refresh issue

- .prettierrc
- src/components/Header.js
Closes #120 
This branch doubles the size of the back arrow.
**Before**
**After**
> Double size of back arrow

- .prettierrc
- src/components/WorkOrder/Edit.js
Closes #117
This branch adds New Time Log button to the Edit Work Order page.
> Add New Time Log button to Edit.js

- package-lock.json
- src/queries/api.js
_Closes #94_
We needed to update the filter manually in our API parameters. Diana's changes to form configuration doesn't update our queries/filters.
> 94 filter technicians

- src/components/WorkOrder/AssignTechnicianFields.js
- src/components/WorkOrder/Image/Camera.js
- src/components/WorkOrder/TimeLogDateTimeFields.js
- src/components/WorkOrderDetails.js
_Closes #114_
also some random cleanup
> 114 Set current time as default for New Time Logs fields

- src/components/App.js
- src/components/Form/BigButton.js
- src/components/Home.js
- src/components/Shared/NavFooter.js
- src/styles/App.css
- src/styles/FormFooter.css.js
- src/styles/NavFooter.css.js
> Add Home button in footer navigation bar

- src/components/Home.js
- src/components/MyWorkOrders.js
- src/components/WorkOrder/New.js
> Change all of the New Work Order icons to plus signs

- src/components/AllWorkOrders.js
- src/components/Form/Button.js
- src/components/Form/SubmitButton.js
- src/components/MyWorkOrders.js
- src/components/WorkOrder/AddImage.js
- src/components/WorkOrder/Edit.js
- src/components/WorkOrderDetails.js
- src/styles/App.css
> Make buttons BIGGER

- src/components/WorkOrder/helpers.js
- src/components/WorkOrderDetails.js
- src/queries/fields.js
> 123 Adds vehicles and technicians to work order details

- src/components/WorkOrder/AssetTypeField.js
- src/components/WorkOrder/helpers.js
- src/queries/api.js
> Select nearby assets based on your current location

- src/components/AllWorkOrders.js
- src/components/MyWorkOrders.js
- src/components/Shared/ListWithSearchAndPages.js
The tricky thing here is balancing the decision on filtering the existing response, or making a new query. We can handle the filtering on the front end with React state, or we can pull in new data with filters by making a new Knack API call.
For now, I'm seeing how much we can get away with on the React side. Refactoring or writing new API queries is a little more involved than I think this features merits at this time...
_Closes #77_
> 77 filter by status

- package-lock.json
- package.json
- public/index.html
- src/components/App.js
- src/components/Header.js
- src/components/UserInfo.js
- src/queries/api.js
- src/queries/fields.js
- src/styles/Header.css.js
> Add user information/settings feature

- src/components/WorkOrder/AssetTypeField.js
- src/components/WorkOrder/formConfig.js
- src/components/WorkOrder/helpers.js
- src/queries/api.js
> Create poll queries for specific asset options

- src/components/WorkOrder/helpers.js
> Add handling for missing fields in Knack API res

- src/components/WorkOrder/Edit.js
- src/components/WorkOrder/New.js
- src/components/WorkOrder/helpers.js
- src/components/WorkOrderDetails.js
- src/constants/api.js
- src/queries/api.js
> Remap fields for New Work Order view API call

- public/index.html
> Change app title

- src/components/App.js
- src/components/Assets/AssetTable.js
- src/components/Assets/Assets.js
- src/components/Assets/fieldConfig.js
- src/components/Assets/helpers.js
- src/components/WorkOrderDetails.js
> Add Detector Links to Signal Details view

- src/components/Assets/Assets.js
> Show number of items inside asset accordion

- src/components/WorkOrder/DateTimeRangePicker.js
- src/components/WorkOrder/TimeLogDateTimeFields.js
- src/constants/colors.js
- src/styles/BigDateTimePicker.js
> Time options skips 12:00PM

- src/components/Assets/Assets.js
- src/components/Assets/fieldConfig.js
- src/components/Assets/helpers.js
- src/queries/api.js
> Add File Attachments to Signals Details view

- src/components/WorkOrder/DateTimeRangePicker.js
> New Work Order view breaks when selecting time before date in Scheduled Date fields

- .gitignore
- netlify.toml
First the cache control was set to a max-age of 60 (for 60 seconds), then:
1. Visited the site to prime the cache in Chrome (https://deploy-preview-205--atd-mobile-signals.netlify.com/login)
2. Immediately reloaded, checked if some of the javascript files were being loaded from memory.
3. Waited 2 minutes, then reloaded the browser. Compared results, it looks like the files were loaded again.
> Netlify Cache

- src/components/Header.js
- src/components/Shared/RefreshIcon.js
- src/styles/Header.css.js
> Add refresh button to header

- src/components/Shared/NavFooter.js
- src/components/WorkOrder/AssetTypeField.js
- src/constants/colors.js
- src/styles/FormFooter.css.js
- src/styles/NavFooter.css.js
> Look into sticky footer nav and form buttons with virtual keyboard on Android devices

- src/components/WorkOrder/AssetTypeField.js
Created to explore solutions for issues found in #195
Closes #207
> Nearby Signals enhancement testing

- src/components/Form/SubmitButton.js
- src/components/Login.js
- src/styles/Login.css.js
> Update Error message on login page

- src/components/Assets/Assets.js
- src/components/Assets/helpers.js
> 429 Error in Signal Details view

- src/components/AllWorkOrders.js
- src/components/Assets/Assets.js
- src/components/MyWorkOrders.js
- src/components/WorkOrder/AddInventoryItemsFields.js
- src/components/WorkOrder/AssetTypeField.js
- src/components/WorkOrder/AssignTechnicianFields.js
- src/components/WorkOrder/Edit.js
- src/components/WorkOrder/NewTimeLog.js
- src/components/WorkOrder/WorkSpecifications.js
- src/components/WorkOrderDetails.js
> Address memory leak warnings from unresolved API requests

- src/components/App.js
> App redirects to login view on refresh or when navigating away and back to app

- package-lock.json
- package.json
- src/components/Assets/Assets.js
- src/components/Assets/helpers.js
- src/components/WorkOrder/UploadImage.js
- src/components/WorkOrderDetails.js
- src/queries/api.js
> Upload image from tablet storage to add to work order

- package-lock.json
- src/components/Shared/ListWithSearchAndPages.js
- src/queries/fields.js
> Add Lead Tech name to index of work orders

- package-lock.json
- package.json
- public/index.html
- src/components/AllWorkOrders.js
- src/components/Assets/Assets.js
- src/components/Home.js
- src/components/Login.js
- src/components/MyWorkOrders.js
- src/components/UserInfo.js
- src/components/WorkOrder/New.js
- src/components/WorkOrderDetails.js
This release candidate is to be used with all signal technicians starting on the week of 12/9/19.
This release includes the following new features:
- Added analytics to monitor usage
- Added app version number to the `UserInfo` dropdown component
> V0.7.0 beta

- src/components/WorkOrder/NewTimeLog.js
- src/constants/api.js
- src/queries/api.js
Closes https://github.com/cityofaustin/atd-data-tech/issues/1217
> Fix Time Log Edit bug

- src/components/WorkOrder/InventoryItemTable.js
- src/components/WorkOrderDetails.js
- src/queries/api.js
- src/queries/fields.js
Closes https://github.com/cityofaustin/atd-data-tech/issues/1216
> Create a `Cancel Inventory Item` Page/Form

- src/components/Assets/Assets.js
- src/components/Form/SubmitButton.js
- src/components/Shared/Header.js
- src/components/Shared/ListWithSearchAndPages.js
- src/components/WorkOrder/EditInventoryItemsFields.js
- src/components/WorkOrder/InventoryItemTable.js
- src/components/WorkOrder/InventoryItems.js
- src/components/WorkOrder/NewTimeLog.js
- src/components/WorkOrder/TimeLog.js
- src/components/WorkOrder/UploadImage.js
- src/components/WorkOrderDetails.js
- src/styles/App.css
Closes cityofaustin/atd-data-tech#1304
##Tablet
> Responsive updates using grid/flex bootstrap classes

- src/components/WorkOrder/TaskOrderField.js
- src/components/WorkOrder/WorkSpecifications.js
> Convert TaskOrderField from multi to single select

- src/components/AllWorkOrders.js
- src/components/App.js
- src/components/Assets/Assets.js
- src/components/Header.js
- src/components/Home.js
- src/components/MyWorkOrders.js
- src/components/Shared/PageTitle.js
- src/components/WorkOrder/Edit.js
- src/components/WorkOrder/New.js
- src/components/WorkOrder/NewTimeLog.js
- src/components/WorkOrderDetails.js
- src/constants/pages.js
- src/styles/Header.css.js
Closes https://github.com/cityofaustin/atd-data-tech/issues/1218
> Move page titles into Header component

- src/components/Shared/ListWithSearchAndPages.js
- src/components/Shared/StatusBadge.js
- src/components/WorkOrder/InventoryItemTable.js
- src/constants/colors.js
- src/constants/statuses.js
- src/styles/WorkOrderInventoryStatus.js
Closes https://github.com/cityofaustin/atd-data-tech/issues/1403
Closes https://github.com/cityofaustin/atd-data-tech/issues/1418
(branched from work started in #255 and refactored)
This PR adds a new component, `StatusBadge`, to render badges in both the Work Orders (list) views and the Inventory Items table in the Work Order Details view. All of the smaller modifications mentioned in these issues are added too.
> Mobile Signals Work Orders | All Work Orders UI Enhancements
